### ISSUE TITLE
Buttons not showing up correctly

### ISSUE THREAD

**Issue by dahacouk** [kendraio/kendra_office#2]
If you look at https://office.kendra.io/node/add/kendra-expense you see normal radio button / checkboxes but they should look like http://office.kendra.org/node/add/kendra-expense and the screenshot
![window_and_create_expense___kendra_office](https://cloud.githubusercontent.com/assets/201752/7632888/c6e8216a-fa48-11e4-9845-3f8e2cd55653.png)

**Comment by iAugur** [comment]
Buttons existed because the core garland theme had been hacked to add a hook_radios theme function to format radios compatible with jquery_ui. 
I have created a template theming function for the radios within the unused koffice them and set the site to use that and the buttons are back.
Test and close if you are happy

**Comment by dahacouk** [comment]
Happy!
